---
title: "DATA_VIS_1"
output: html_document
date: "2022-11-21"
---

```{r setup, include = FALSE}
# Loading of Dataset
student_all <- read.csv(file = "C:/SBE/Data_vis/DATA_VIS_1/data/student.csv",
                  stringsAsFactors = FALSE)

student_all
str(student_all)
summary(student_all)

install.packages("corrplot")
library(corrplot)


```
```{r}
set.seed(32)
student = student_all[sample(nrow(student_all), size = 600),]
```
## Check for Missing values
``` {r}
missing_student <- is.na.data.frame(student)
which(missing_student)
```
## Identify outliers using numerical method
```{r}
variable_stats = student$g3
IQR_data <- c(summary(variable_stats))
names(IQR_data) <- NULL
IQR_Q3 <- IQR_data[5]
IQR_Q1 <- IQR_data[2]
IQR <- IQR_Q3 - IQR_Q1
normal_data_range_lower <- IQR_Q1 - 1.5 * IQR
normal_data_range_higher <- IQR_Q3 + 1.5 * IQR
IQR.outliers <- (0:19) > normal_data_range_higher | (0:19) < normal_data_range_lower
names(IQR.outliers) <- c(0:19)
IQR.outliers

hist(variable_stats,
     col = "darkred",
     border = "black",
     xlab = "Grade",
     ylab = "Frequency",
     main = "Histogram of Grades all Students")
``` 
## Show important relationships to target variable -- STATS
```{r}
student$pass_or_fail = student$g3

for (i in 1:length(student$g3)) {
  if(student$g3[i] >= 11)
   student$pass_or_fail[i] = 'passed'
  if(student$g3[i] < 11)
   student$pass_or_fail[i] = 'failed'
     
}

```
## Show important realtionships to target variable -- VISUAL
```{r}


```
## Correlation Analysis -- Numerical
```{r}
# Collect variables of interest
corrdata <- cbind(student$age,
                  student$medu,
                  student$fedu,
                  student$traveltime,
                  student$studytime,
                  student$failures,
                  student$famrel,
                  student$freetime,
                  student$goout,
                  student$dalc,
                  student$walc,
                  student$health,
                  student$absences,
                  student$g1,
                  student$g2,
                  student$g3)
# Declare the matrix
corrpvalues <- matrix(rep(0, 25),
ncol = 5)
# Fill the matrix with correlations
for (i in 1:4) {
for (j in (i+1):5) {
corrpvalues[i,j] <- corrpvalues[j,i] <-
round(cor.test(corrdata[,i],
corrdata[,j])$p.value,
4)
}
}

cor_matrix = cor(corrdata)
rownames(cor_matrix) <- c("age","medu","fedu","traveltime","studytime","failures","famrel","freetime","goout","dalc","walc","health","absences","g1","g2","g3")
colnames(cor_matrix) <- c("age","medu","fedu","traveltime","studytime","failures","famrel","freetime","goout","dalc","walc","health","absences","g1","g2","g3")
corrplot(cor_matrix, method="number", col.lab = "black")
```
## Frequency Analysis -- Categorical



## Interpetation

## Summary/Conclusion 

